import type {Metadata} from 'next'
import {Montserrat} from 'next/font/google'
import './globals.css'

const mont = Montserrat({subsets: ['latin'], variable: '--f-mont'})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
   children
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={mont.variable}>{children}</body>
        </html>
    )
}
